version: "3.9"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
    args:
      RUBY_VERSION: 3.1.3
      PG_MAJOR: 14
      NODE_MAJOR: 18
      YARN_VERSION: 1.22.19
  env_file:
    - .env
  tty: true
  volumes:
    - .:/app:cached
    - node_modules:/app/node_modules
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle

x-backend: &backend
  <<: *app

services:
  runner:
    <<: *backend
    command: /bin/bash

  web:
    <<: *backend
    command: sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - 3000:3000
    depends_on:
      - postgres

  js:
    <<: *app
    command: yarn build --watch

  css:
    <<: *app
    command: yarn build:css --watch

  postgres:
    image: postgres:14-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: servicee_development
      POSTGRES_USER: servicee_user
      POSTGRES_PASSWORD: ${SERVICEE_DATABASE_PASSWORD}
    ports:
      - 5433:5432
  redis:
    image: redis
    volumes:
      - redis_data:/data

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
  redis_data:

