default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV["PGHOST"] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: servicee_user
  password: <%= ENV["SERVICEE_DATABASE_PASSWORD"] %>

development:
  <<: *default
  database: servicee_development

  
test:
  <<: *default
  database: servicee_test


production:
  <<: *default
  database: servicee_production
